/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const JobId = IDL.Nat;
export const JobListing = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
  'poster' : IDL.Principal,
});
export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : CommentId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : Time,
  'comments' : IDL.Vec(Comment),
});
export const Profile = IDL.Record({
  'principal' : IDL.Principal,
  'headline' : IDL.Text,
  'name' : IDL.Text,
  'education' : IDL.Vec(IDL.Text),
  'experience' : IDL.Vec(IDL.Text),
  'isCompany' : IDL.Bool,
  'skills' : IDL.Vec(IDL.Text),
});
export const Connection = IDL.Record({
  'user1' : IDL.Principal,
  'user2' : IDL.Principal,
});
export const MessageId = IDL.Nat;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'receiver' : IDL.Principal,
});

export const idlService = IDL.Service({
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [JobId],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
  'createPost' : IDL.Func([IDL.Text], [PostId], []),
  'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getConnectionRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Connection)],
      ['query'],
    ),
  'getConnections' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Connection)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'respondToConnectionRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'sendConnectionRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [MessageId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const JobId = IDL.Nat;
  const JobListing = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
    'poster' : IDL.Principal,
  });
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : CommentId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : Time,
    'comments' : IDL.Vec(Comment),
  });
  const Profile = IDL.Record({
    'principal' : IDL.Principal,
    'headline' : IDL.Text,
    'name' : IDL.Text,
    'education' : IDL.Vec(IDL.Text),
    'experience' : IDL.Vec(IDL.Text),
    'isCompany' : IDL.Bool,
    'skills' : IDL.Vec(IDL.Text),
  });
  const Connection = IDL.Record({
    'user1' : IDL.Principal,
    'user2' : IDL.Principal,
  });
  const MessageId = IDL.Nat;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'receiver' : IDL.Principal,
  });
  
  return IDL.Service({
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [JobId],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
    'createPost' : IDL.Func([IDL.Text], [PostId], []),
    'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getConnectionRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Connection)],
        ['query'],
      ),
    'getConnections' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Connection)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'respondToConnectionRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'sendConnectionRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [MessageId], []),
  });
};

export const init = ({ IDL }) => { return []; };