/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type CommentId = bigint;
export interface Connection { 'user1' : Principal, 'user2' : Principal }
export type JobId = bigint;
export interface JobListing {
  'id' : JobId,
  'title' : string,
  'description' : string,
  'company' : string,
  'requirements' : Array<string>,
  'location' : string,
  'poster' : Principal,
}
export interface Message {
  'id' : MessageId,
  'content' : string,
  'sender' : Principal,
  'timestamp' : Time,
  'receiver' : Principal,
}
export type MessageId = bigint;
export interface Post {
  'id' : PostId,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : Time,
  'comments' : Array<Comment>,
}
export type PostId = bigint;
export interface Profile {
  'principal' : Principal,
  'headline' : string,
  'name' : string,
  'education' : Array<string>,
  'experience' : Array<string>,
  'isCompany' : boolean,
  'skills' : Array<string>,
}
export type Time = bigint;
export interface _SERVICE {
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'createJobListing' : ActorMethod<
    [string, string, string, string, Array<string>],
    JobId
  >,
  'createOrUpdateProfile' : ActorMethod<
    [string, string, Array<string>, Array<string>, Array<string>, boolean],
    undefined
  >,
  'createPost' : ActorMethod<[string], PostId>,
  'getAllJobListings' : ActorMethod<[], Array<JobListing>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getConnectionRequests' : ActorMethod<[Principal], Array<Connection>>,
  'getConnections' : ActorMethod<[Principal], Array<Connection>>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getProfile' : ActorMethod<[Principal], Profile>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'respondToConnectionRequest' : ActorMethod<[Principal, boolean], undefined>,
  'sendConnectionRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], MessageId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];