/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CommentId = bigint;
export type Time = bigint;
export interface Comment {
    id: CommentId;
    content: string;
    author: Principal;
    timestamp: Time;
}
export type MessageId = bigint;
export type PostId = bigint;
export interface Post {
    id: PostId;
    content: string;
    author: Principal;
    likes: Array<Principal>;
    timestamp: Time;
    comments: Array<Comment>;
}
export interface Message {
    id: MessageId;
    content: string;
    sender: Principal;
    timestamp: Time;
    receiver: Principal;
}
export type JobId = bigint;
export interface JobListing {
    id: JobId;
    title: string;
    description: string;
    company: string;
    requirements: Array<string>;
    location: string;
    poster: Principal;
}
export interface Profile {
    principal: Principal;
    headline: string;
    name: string;
    education: Array<string>;
    experience: Array<string>;
    isCompany: boolean;
    skills: Array<string>;
}
export interface Connection {
    user1: Principal;
    user2: Principal;
}
export interface backendInterface {
    addComment(postId: PostId, content: string): Promise<CommentId>;
    createJobListing(title: string, company: string, description: string, location: string, requirements: Array<string>): Promise<JobId>;
    createOrUpdateProfile(name: string, headline: string, experience: Array<string>, skills: Array<string>, education: Array<string>, isCompany: boolean): Promise<void>;
    createPost(content: string): Promise<PostId>;
    getAllJobListings(): Promise<Array<JobListing>>;
    getAllPosts(): Promise<Array<Post>>;
    getAllProfiles(): Promise<Array<Profile>>;
    getConnectionRequests(user: Principal): Promise<Array<Connection>>;
    getConnections(user: Principal): Promise<Array<Connection>>;
    getMessages(user: Principal): Promise<Array<Message>>;
    getProfile(principal: Principal): Promise<Profile>;
    likePost(postId: PostId): Promise<void>;
    respondToConnectionRequest(from: Principal, accept: boolean): Promise<void>;
    sendConnectionRequest(to: Principal): Promise<void>;
    sendMessage(receiver: Principal, content: string): Promise<MessageId>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addComment(arg0: PostId, arg1: string): Promise<CommentId> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async createJobListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<JobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobListing(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<string>, arg4: Array<string>, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createPost(arg0: string): Promise<PostId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0);
            return result;
        }
    }
    async getAllJobListings(): Promise<Array<JobListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobListings();
            return result;
        }
    }
    async getAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return result;
        }
    }
    async getAllProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return result;
        }
    }
    async getConnectionRequests(arg0: Principal): Promise<Array<Connection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnectionRequests(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnectionRequests(arg0);
            return result;
        }
    }
    async getConnections(arg0: Principal): Promise<Array<Connection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConnections(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConnections(arg0);
            return result;
        }
    }
    async getMessages(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getProfile(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async respondToConnectionRequest(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToConnectionRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToConnectionRequest(arg0, arg1);
            return result;
        }
    }
    async sendConnectionRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendConnectionRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendConnectionRequest(arg0);
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
